In [1]:
from Softmax_model.Softmax import SoftmaxClassifier
from Decision_Trees_model.decision_trees import DecisionTree_classification
from Decision_Trees_model.decision_trees import RandomForest_classification
from Decision_Trees_model.decision_trees import GBDT_with_sklearn_classification
from Neural_Network_model.MLP_network import MLP_network
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine
from joblib import dump, load
import pandas as pd
import numpy as np
import os

In [8]:
train = pd.read_csv('Datasets/har_train.csv')
test = pd.read_csv('Datasets/har_test.csv')

x_train = train.drop(['Activity', 'subject'], axis=1).to_numpy()
y_train = train['Activity'].to_numpy()

x_test = test.drop(['Activity', 'subject'], axis=1).to_numpy()
y_test = test['Activity'].to_numpy()

print("========== Dataset: Human Activity Recognition ==========")
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)

print("Softmax selfmade:")
softmax_file = "softmax_model_har.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = SoftmaxClassifier(
        learning_rate=0.1,
        max_iter=100000,
        eps=1e-4,
        lambda_reg=0.05,
        use_pca=True,
        n_components=0.95
    )
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_model_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nSoftmax library:")
softmax_file = "softmax_sklearn_har.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = LogisticRegression(solver="saga", max_iter=10000, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_sklearn_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree selfmade:")
tree_file = "decision_tree_model_har.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTree_classification(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_model_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree library:")
tree_file = "decision_tree_sklearn_har.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTreeClassifier(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_sklearn_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest selfmade:")
forest_file = "random_forest_model_har.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForest_classification(max_depth=8, n_trees=50, method="sqrt")
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_model_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest library:")
forest_file = "random_forest_sklearn_har.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForestClassifier(max_depth=8, n_estimators=50, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_sklearn_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees selfmade:")
gbdt_file = "gbdt_model_har.joblib"

if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = GBDT_with_sklearn_classification(n_estimators=50, max_depth=8, learning_rate=0.1,
                                         subsample=0.85, min_samples_split=20)
    model.fit(x_train, y_train)
    dump(model, "Saved models/gbdt_model_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees library:")
gbdt_file = "gbdt_xgbc_har.joblib"
if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = XGBClassifier(n_estimators=50, max_depth=8)
    model.fit(x_train, y_train_enc, eval_set=[(x_train, y_train_enc)], verbose=False)
    dump(model, "Saved models/gbdt_xgbc_har.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP selfmade:")
mpl_file = "mlp_model_har.joblib"

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLP_network(lambda_reg=0.001)
    model.fit(x_train_scaled, y_train_enc, verbose=True)
    dump(model, "Saved models/mlp_model_har.joblib")

y_pred = model.predict(x_test_scaled)
y_pred_train = model.predict(x_train_scaled)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP library:")
mpl_file = "mlp_sklearn_har.joblib"

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLPClassifier(
        hidden_layer_sizes=(256, 128, 64, 32),
        activation='relu',
        solver='adam',
        alpha=0.001,
        learning_rate_init=0.01,
        max_iter=1000,
        early_stopping=True,
        n_iter_no_change=20,
        validation_fraction=0.1,
        random_state=42,
        verbose=False
    )
    model.fit(x_train_scaled, y_train_enc)
    dump(model, "Saved models/mlp_sklearn_har.joblib")

y_pred_enc = model.predict(x_test_scaled)
y_pred_train_enc = model.predict(x_train_scaled)
y_pred = le.inverse_transform(y_pred_enc)
y_pred_train = le.inverse_transform(y_pred_train_enc)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")

========== Dataset: Human Activity Recognition ==========
Softmax selfmade:
Обучение модели:


  3%|▎         | 2650/100000 [00:09<05:55, 273.86it/s]


Accuracy on test: 0.9345096708517137
Accuracy on train: 0.9639553862894451
Confusion matrix: 
[[530   0   7   0   0   0]
 [  1 428  59   0   0   3]
 [  0  38 494   0   0   0]
 [  0   0   0 491   5   0]
 [  0   0   0  16 369  35]
 [  0   0   1  25   3 442]]
Classification report: 
                    precision    recall  f1-score   support

            LAYING       1.00      0.99      0.99       537
           SITTING       0.92      0.87      0.89       491
          STANDING       0.88      0.93      0.90       532
           WALKING       0.92      0.99      0.96       496
WALKING_DOWNSTAIRS       0.98      0.88      0.93       420
  WALKING_UPSTAIRS       0.92      0.94      0.93       471

          accuracy                           0.93      2947
         macro avg       0.94      0.93      0.93      2947
      weighted avg       0.94      0.93      0.93      2947


Softmax library:
Accuracy on test: 0.9609772650152698
Accuracy on train: 0.9925190424374319
Confusion matrix: 
[[53

100%|██████████| 50/50 [26:31<00:00, 31.84s/it]


Accuracy on test: 0.9053274516457415
Accuracy on train: 0.985310119695321
Confusion matrix: 
[[523   7   7   0   0   0]
 [  8 367 115   0   0   1]
 [  0   6 526   0   0   0]
 [  0   0   0 489   6   1]
 [  0   0   0  33 333  54]
 [  0   0   0  34   7 430]]
Classification report: 
                    precision    recall  f1-score   support

            LAYING       0.98      0.97      0.98       537
           SITTING       0.97      0.75      0.84       491
          STANDING       0.81      0.99      0.89       532
           WALKING       0.88      0.99      0.93       496
WALKING_DOWNSTAIRS       0.96      0.79      0.87       420
  WALKING_UPSTAIRS       0.88      0.91      0.90       471

          accuracy                           0.91      2947
         macro avg       0.91      0.90      0.90      2947
      weighted avg       0.91      0.91      0.90      2947


Random Forest library:
Accuracy on test: 0.9144893111638955
Accuracy on train: 0.9863982589771491
Confusion matrix: 

Обучение GBDT: 100%|██████████| 50/50 [14:52<00:00, 17.85s/it]


Accuracy on test: 0.9019341703427214
Accuracy on train: 0.999455930359086
Confusion matrix: 
[[537   0   0   0   0   0]
 [  0 392  96   0   0   3]
 [  0  56 475   0   0   1]
 [  1   2   0 462  13  18]
 [  8   0   1  15 371  25]
 [  2   1   0  40   7 421]]
Classification report: 
                    precision    recall  f1-score   support

            LAYING       0.98      1.00      0.99       537
           SITTING       0.87      0.80      0.83       491
          STANDING       0.83      0.89      0.86       532
           WALKING       0.89      0.93      0.91       496
WALKING_DOWNSTAIRS       0.95      0.88      0.91       420
  WALKING_UPSTAIRS       0.90      0.89      0.90       471

          accuracy                           0.90      2947
         macro avg       0.90      0.90      0.90      2947
      weighted avg       0.90      0.90      0.90      2947


Gradient Boosting Decision Trees library:
Accuracy on test: 0.9280624363759755
Accuracy on train: 1.0
Confusion matr

Обучение MLP:   0%|          | 0/1000 [00:00<?, ?it/s]

Эпоха 0, loss=2.663143


Обучение MLP:  20%|██        | 202/1000 [00:24<01:37,  8.16it/s]

Эпоха 200, loss=0.709642


Обучение MLP:  40%|████      | 402/1000 [00:47<01:04,  9.23it/s]

Эпоха 400, loss=0.605765


Обучение MLP:  60%|██████    | 602/1000 [01:12<00:43,  9.18it/s]

Эпоха 600, loss=0.567273


Обучение MLP:  70%|███████   | 702/1000 [01:23<00:35,  8.45it/s]


Остановка на 702 эпохе, change=9.98e-05<eps=0.0001
Accuracy on test: 0.9260264675941635
Accuracy on train: 0.9793253536452666
Confusion matrix: 
[[535   0   1   0   0   1]
 [  1 425  62   0   0   3]
 [  0  36 496   0   0   0]
 [  0   0   0 475  10  11]
 [  0   0   0  26 356  38]
 [  0   0   0  24   5 442]]
Classification report: 
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.92      0.87      0.89       491
          STANDING       0.89      0.93      0.91       532
           WALKING       0.90      0.96      0.93       496
WALKING_DOWNSTAIRS       0.96      0.85      0.90       420
  WALKING_UPSTAIRS       0.89      0.94      0.92       471

          accuracy                           0.93      2947
         macro avg       0.93      0.92      0.92      2947
      weighted avg       0.93      0.93      0.93      2947


MLP library:
Accuracy on test: 0.9436715303698676
Accuracy on tr

In [9]:
data_wine = load_wine()
wine_df = pd.DataFrame(data_wine.data, columns=data_wine.feature_names)
wine_df['target'] = data_wine.target_names[data_wine.target]

wine_map = {'class_0': 'Производитель 1', 'class_1': 'Производитель 2', 'class_2': 'Производитель 3'}
wine_df['target'] = wine_df['target'].map(wine_map)

x_wine = wine_df.drop(['target'], axis=1).copy().to_numpy()
y_wine = wine_df['target'].copy().to_numpy()

x_train, x_test, y_train, y_test = train_test_split(x_wine, y_wine, test_size=0.3, random_state=42)


print("========== Dataset: Wine manufacturer ==========")
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)

print("Softmax selfmade:")
softmax_file = "softmax_model_wine.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = SoftmaxClassifier(
        learning_rate=0.1,
        max_iter=100000,
        eps=1e-4,
        lambda_reg=0.05,
        use_pca=True,
        n_components=0.95
    )
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_model_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nSoftmax library:")
softmax_file = "softmax_sklearn_wine.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = LogisticRegression(solver="saga", max_iter=10000, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_sklearn_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree selfmade:")
tree_file = "decision_tree_model_wine.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTree_classification(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_model_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree library:")
tree_file = "decision_tree_sklearn_wine.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTreeClassifier(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_sklearn_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest selfmade:")
forest_file = "random_forest_model_wine.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForest_classification(max_depth=8, n_trees=50, method="sqrt")
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_model_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest library:")
forest_file = "random_forest_sklearn_wine.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForestClassifier(max_depth=8, n_estimators=50, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_sklearn_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees selfmade:")
gbdt_file = "gbdt_model_wine.joblib"

if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = GBDT_with_sklearn_classification(n_estimators=50, max_depth=8, learning_rate=0.1,
                                         subsample=0.85, min_samples_split=20)
    model.fit(x_train, y_train)
    dump(model, "Saved models/gbdt_model_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees library:")
gbdt_file = "gbdt_xgbc_wine.joblib"
if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = XGBClassifier(n_estimators=50, max_depth=8)
    model.fit(x_train, y_train_enc, eval_set=[(x_train, y_train_enc)], verbose=False)
    dump(model, "Saved models/gbdt_xgbc_wine.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP selfmade:")
mpl_file = "mlp_model_wine.joblib"

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLP_network(lambda_reg=0.001)
    model.fit(x_train_scaled, y_train_enc, verbose=True)
    dump(model, "Saved models/mlp_model_wine.joblib")

y_pred = model.predict(x_test_scaled)
y_pred_train = model.predict(x_train_scaled)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP library:")
mpl_file = "mlp_sklearn_wine.joblib"

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLPClassifier(
        hidden_layer_sizes=(256, 128, 64, 32),
        activation='relu',
        solver='adam',
        alpha=0.001,
        learning_rate_init=0.01,
        max_iter=1000,
        early_stopping=True,
        n_iter_no_change=20,
        validation_fraction=0.1,
        random_state=42,
        verbose=False
    )
    model.fit(x_train_scaled, y_train_enc)
    dump(model, "Saved models/mlp_sklearn_wine.joblib")

y_pred_enc = model.predict(x_test_scaled)
y_pred_train_enc = model.predict(x_train_scaled)
y_pred = le.inverse_transform(y_pred_enc)
y_pred_train = le.inverse_transform(y_pred_train_enc)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")

========== Dataset: Wine manufacturer ==========
Softmax selfmade:
Обучение модели:


  1%|          | 959/100000 [00:00<00:05, 17584.45it/s]

Accuracy on test: 1.0
Accuracy on train: 0.9919354838709677
Confusion matrix: 
[[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       1.00      1.00      1.00        19
Производитель 2       1.00      1.00      1.00        21
Производитель 3       1.00      1.00      1.00        14

       accuracy                           1.00        54
      macro avg       1.00      1.00      1.00        54
   weighted avg       1.00      1.00      1.00        54


Softmax library:


Accuracy on test: 0.9814814814814815
Accuracy on train: 0.9193548387096774
Confusion matrix: 
[[19  0  0]
 [ 0 21  0]
 [ 1  0 13]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       0.95      1.00      0.97        19
Производитель 2       1.00      1.00      1.00        21
Производитель 3       1.00      0.93      0.96        14

       accuracy                           0.98        54
      macro avg       0.98      0.98      0.98        54
   weighted avg       0.98      0.98      0.98        54


Decision Tree selfmade:
Accuracy on test: 0.8333333333333334
Accuracy on train: 0.9758064516129032
Confusion matrix: 
[[17  2  0]
 [ 2 18  1]
 [ 2  2 10]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       0.81      0.89      0.85        19
Производитель 2       0.82      0.86      0.84        21
Производитель 3       0.91      0.71      0.80        14

       accuracy                  

100%|██████████| 50/50 [00:04<00:00, 10.04it/s]


Accuracy on test: 0.9814814814814815
Accuracy on train: 1.0
Confusion matrix: 
[[19  0  0]
 [ 0 20  1]
 [ 0  0 14]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       1.00      1.00      1.00        19
Производитель 2       1.00      0.95      0.98        21
Производитель 3       0.93      1.00      0.97        14

       accuracy                           0.98        54
      macro avg       0.98      0.98      0.98        54
   weighted avg       0.98      0.98      0.98        54


Random Forest library:
Accuracy on test: 1.0
Accuracy on train: 1.0
Confusion matrix: 
[[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       1.00      1.00      1.00        19
Производитель 2       1.00      1.00      1.00        21
Производитель 3       1.00      1.00      1.00        14

       accuracy                           1.00        54
      macro avg       

Обучение GBDT: 100%|██████████| 50/50 [00:00<00:00, 257.15it/s]


Accuracy on test: 0.9814814814814815
Accuracy on train: 1.0
Confusion matrix: 
[[18  1  0]
 [ 0 21  0]
 [ 0  0 14]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       1.00      0.95      0.97        19
Производитель 2       0.95      1.00      0.98        21
Производитель 3       1.00      1.00      1.00        14

       accuracy                           0.98        54
      macro avg       0.98      0.98      0.98        54
   weighted avg       0.98      0.98      0.98        54


Gradient Boosting Decision Trees library:
Accuracy on test: 0.9629629629629629
Accuracy on train: 1.0
Confusion matrix: 
[[19  0  0]
 [ 1 20  0]
 [ 0  1 13]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       0.95      1.00      0.97        19
Производитель 2       0.95      0.95      0.95        21
Производитель 3       1.00      0.93      0.96        14

       accuracy                           0.9

Обучение MLP:   5%|▍         | 46/1000 [00:00<00:02, 457.98it/s]

Эпоха 0, loss=2.116121


Обучение MLP:  21%|██        | 207/1000 [00:00<00:01, 402.40it/s]


Эпоха 200, loss=0.503631
Остановка на 207 эпохе, change=9.91e-05<eps=0.0001
Accuracy on test: 0.9629629629629629
Accuracy on train: 1.0
Confusion matrix: 
[[19  0  0]
 [ 2 19  0]
 [ 0  0 14]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       0.90      1.00      0.95        19
Производитель 2       1.00      0.90      0.95        21
Производитель 3       1.00      1.00      1.00        14

       accuracy                           0.96        54
      macro avg       0.97      0.97      0.97        54
   weighted avg       0.97      0.96      0.96        54


MLP library:
Accuracy on test: 0.9444444444444444
Accuracy on train: 0.9919354838709677
Confusion matrix: 
[[17  2  0]
 [ 0 21  0]
 [ 1  0 13]]
Classification report: 
                 precision    recall  f1-score   support

Производитель 1       0.94      0.89      0.92        19
Производитель 2       0.91      1.00      0.95        21
Производитель 3       1.00      0.93     

In [10]:
data_iris = load_iris()
iris_df = pd.DataFrame(data_iris.data, columns=data_iris.feature_names)
iris_df['target'] = data_iris.target_names[data_iris.target]

x_iris = iris_df.drop(['target'], axis=1).copy().to_numpy()
y_iris = iris_df['target'].copy().to_numpy()

x_train, x_test, y_train, y_test = train_test_split(x_iris, y_iris, test_size=0.3, random_state=42)


print("========== Dataset: Iris type ==========")
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)

print("Softmax selfmade:")
softmax_file = "softmax_model_iris.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = SoftmaxClassifier(
        learning_rate=0.1,
        max_iter=100000,
        eps=1e-4,
        lambda_reg=0.05,
        use_pca=True,
        n_components=0.95
    )
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_model_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nSoftmax library:")
softmax_file = "softmax_sklearn_iris.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = LogisticRegression(solver="saga", max_iter=10000, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_sklearn_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree selfmade:")
tree_file = "decision_tree_model_iris.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTree_classification(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_model_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree library:")
tree_file = "decision_tree_sklearn_iris.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTreeClassifier(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_sklearn_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest selfmade:")
forest_file = "random_forest_model_iris.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForest_classification(max_depth=8, n_trees=50, method="sqrt")
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_model_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest library:")
forest_file = "random_forest_sklearn_iris.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForestClassifier(max_depth=8, n_estimators=50, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_sklearn_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees selfmade:")
gbdt_file = "gbdt_model_iris.joblib"

if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = GBDT_with_sklearn_classification(n_estimators=50, max_depth=8, learning_rate=0.1,
                                         subsample=0.85, min_samples_split=20)
    model.fit(x_train, y_train)
    dump(model, "Saved models/gbdt_model_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees library:")
gbdt_file = "gbdt_xgbc_iris.joblib"
if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = XGBClassifier(n_estimators=50, max_depth=8)
    model.fit(x_train, y_train_enc, eval_set=[(x_train, y_train_enc)], verbose=False)
    dump(model, "Saved models/gbdt_xgbc_iris.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP selfmade:")
mpl_file = "mlp_model_iris.joblib"

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLP_network(lambda_reg=0.001)
    model.fit(x_train_scaled, y_train_enc, verbose=True)
    dump(model, "Saved models/mlp_model_iris.joblib")

y_pred = model.predict(x_test_scaled)
y_pred_train = model.predict(x_train_scaled)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP library:")
mpl_file = "mlp_sklearn_iris.joblib"

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLPClassifier(
        hidden_layer_sizes=(256, 128, 64, 32),
        activation='relu',
        solver='adam',
        alpha=0.001,
        learning_rate_init=0.01,
        max_iter=1000,
        early_stopping=True,
        n_iter_no_change=20,
        validation_fraction=0.1,
        random_state=42,
        verbose=False
    )
    model.fit(x_train_scaled, y_train_enc)
    dump(model, "Saved models/mlp_sklearn_iris.joblib")

y_pred_enc = model.predict(x_test_scaled)
y_pred_train_enc = model.predict(x_train_scaled)
y_pred = le.inverse_transform(y_pred_enc)
y_pred_train = le.inverse_transform(y_pred_train_enc)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")

========== Dataset: Iris type ==========
Softmax selfmade:
Обучение модели:


  1%|          | 650/100000 [00:00<00:05, 19215.92it/s]


Accuracy on test: 0.8666666666666667
Accuracy on train: 0.8761904761904762
Confusion matrix: 
[[19  0  0]
 [ 0  8  5]
 [ 0  1 12]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.89      0.62      0.73        13
   virginica       0.71      0.92      0.80        13

    accuracy                           0.87        45
   macro avg       0.86      0.85      0.84        45
weighted avg       0.88      0.87      0.86        45


Softmax library:
Accuracy on test: 1.0
Accuracy on train: 0.9714285714285714
Confusion matrix: 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00 

100%|██████████| 50/50 [00:01<00:00, 40.02it/s]


Accuracy on test: 1.0
Accuracy on train: 0.9619047619047619
Confusion matrix: 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Random Forest library:
Accuracy on test: 1.0
Accuracy on train: 1.0
Confusion matrix: 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weig

Обучение GBDT: 100%|██████████| 50/50 [00:00<00:00, 444.15it/s]


Accuracy on test: 1.0
Accuracy on train: 0.9904761904761905
Confusion matrix: 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Gradient Boosting Decision Trees library:
Accuracy on test: 1.0
Accuracy on train: 1.0
Confusion matrix: 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      

Обучение MLP:   4%|▍         | 39/1000 [00:00<00:02, 381.57it/s]

Эпоха 0, loss=2.301440


Обучение MLP:  27%|██▋       | 271/1000 [00:00<00:01, 480.15it/s]

Эпоха 200, loss=0.639251


Обучение MLP:  48%|████▊     | 475/1000 [00:01<00:01, 472.70it/s]

Эпоха 400, loss=0.585694


Обучение MLP:  54%|█████▍    | 539/1000 [00:01<00:01, 455.08it/s]


Остановка на 539 эпохе, change=9.74e-05<eps=0.0001
Accuracy on test: 0.9777777777777777
Accuracy on train: 0.9809523809523809
Confusion matrix: 
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      0.92      0.96        13
   virginica       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45


MLP library:
Accuracy on test: 0.8444444444444444
Accuracy on train: 0.8761904761904762
Confusion matrix: 
[[19  0  0]
 [ 0  6  7]
 [ 0  0 13]]
Classification report: 
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      0.46      0.63        13
   virginica       0.65      1.00      0.79        13

    accuracy              

In [11]:
credit_train_df = pd.read_csv("Datasets/credit_cleaned_train.csv", low_memory=False)
credit_train_df = credit_train_df.drop(columns=['ID', 'Customer_ID', 'Month', 'Name', 'SSN'], axis=1)

print("Credit Score distribution:", np.unique(credit_train_df['Credit_Score'], return_counts=True))

type_of_loan_position = credit_train_df.columns.get_loc('Type_of_Loan')

loan_map = {'No Data': 'No Data loan', 'not specified': 'not specified loan'}
credit_train_df['Type_of_Loan'] = credit_train_df['Type_of_Loan'].map(loan_map)

main_loan_types = [
    'No Data loan',
    'not specified loan',
    'credit-builder loan',
    'personal loan',
    'debt consolidation loan',
    'student loan',
    'payday loan',
    'mortgage loan',
    'auto loan',
    'home equity loan'
]

def process_loans(loan_string):
    if pd.isna(loan_string):
        result = np.zeros(len(main_loan_types))
        result[main_loan_types.index('No Data loan')] = 1
        return result

    loan_str = str(loan_string)
    loan_lower = loan_str.lower()

    result = np.zeros(len(main_loan_types))

    if 'no data loan' in loan_lower:
        result[main_loan_types.index('No Data loan')] = 1
        return result

    loans = [loan.strip() for loan in loan_str.split(',')]

    for loan in loans:
        loan_lower = loan.lower()
        found = False

        for i, loan_type in enumerate(main_loan_types[2:]):
            if loan_type in loan_lower:
                result[i+2] += 1
                found = True
                break


    return result

loan_vectors = credit_train_df['Type_of_Loan'].apply(process_loans)

for i, loan_type in enumerate(main_loan_types):
    col_name = loan_type.replace(" ", "_").replace("-", "_")
    credit_train_df[f'has_{col_name}'] = loan_vectors.apply(lambda x: 1 if x[i] > 0 else 0)

credit_train_df.drop('Type_of_Loan', axis=1, inplace=True)

all_columns = credit_train_df.columns.tolist()

new_columns = [col for col in all_columns if col.startswith('has_')]

for col in new_columns:
    all_columns.remove(col)

all_columns = all_columns[:type_of_loan_position] + new_columns + all_columns[type_of_loan_position:]
credit_train_df = credit_train_df[all_columns]

categorical_columns = ['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour']

column_positions = {}
for col in categorical_columns:
    column_positions[col] = credit_train_df.columns.get_loc(col)

credit_train_df = pd.get_dummies(credit_train_df, columns=categorical_columns, prefix=categorical_columns)

bool_columns = credit_train_df.select_dtypes(include=['bool']).columns
credit_train_df[bool_columns] = credit_train_df[bool_columns].astype(int)

all_columns = credit_train_df.columns.tolist()

for col in categorical_columns:
    one_hot_cols = [c for c in all_columns if c.startswith(col + '_')]

    for one_hot_col in one_hot_cols:
        all_columns.remove(one_hot_col)

    position = column_positions[col]
    all_columns = all_columns[:position] + one_hot_cols + all_columns[position:]

credit_train_df = credit_train_df[all_columns]

x_credit = credit_train_df.drop('Credit_Score', axis=1).to_numpy()
y_credit = credit_train_df['Credit_Score'].to_numpy()

x_train, x_test, y_train, y_test = train_test_split(x_credit, y_credit, test_size=0.3, random_state=42)

Credit Score distribution: (array(['Good', 'Poor', 'Standard'], dtype=object), array([17828, 28998, 53174]))


In [12]:
print("========== Dataset: Credit Score ==========")
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)

print("Softmax selfmade:")
softmax_file = "softmax_model_credit.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = SoftmaxClassifier(
        learning_rate=0.1,
        max_iter=100000,
        eps=1e-4,
        lambda_reg=0.05,
        use_pca=True,
        n_components=0.95
    )
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_model_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nSoftmax library:")
softmax_file = "softmax_sklearn_credit.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = LogisticRegression(solver="saga", max_iter=10000, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_sklearn_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree selfmade:")
tree_file = "decision_tree_model_credit.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTree_classification(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_model_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree library:")
tree_file = "decision_tree_sklearn_credit.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTreeClassifier(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_sklearn_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest selfmade:")
forest_file = "random_forest_model_credit.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForest_classification(max_depth=8, n_trees=50, method="sqrt")
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_model_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nRandom Forest library:")
forest_file = "random_forest_sklearn_credit.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForestClassifier(max_depth=8, n_estimators=50, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_sklearn_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees selfmade:")
gbdt_file = "gbdt_model_credit.joblib"

if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = GBDT_with_sklearn_classification(n_estimators=50, max_depth=8, learning_rate=0.1,
                                         subsample=0.85, min_samples_split=20)
    model.fit(x_train, y_train)
    dump(model, "Saved models/gbdt_model_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees library:")
gbdt_file = "gbdt_xgbc_credit.joblib"
if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = XGBClassifier(n_estimators=50, max_depth=8)
    model.fit(x_train, y_train_enc, eval_set=[(x_train, y_train_enc)], verbose=False)
    dump(model, "Saved models/gbdt_xgbc_credit.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP selfmade:")
mpl_file = "mlp_model_credit.joblib"

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLP_network(lambda_reg=0.001)
    model.fit(x_train_scaled, y_train_enc, verbose=True)
    dump(model, "Saved models/mlp_model_credit.joblib")

y_pred = model.predict(x_test_scaled)
y_pred_train = model.predict(x_train_scaled)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP library:")
mpl_file = "mlp_sklearn_credit.joblib"

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLPClassifier(
        hidden_layer_sizes=(256, 128, 64, 32),
        activation='relu',
        solver='adam',
        alpha=0.001,
        learning_rate_init=0.01,
        max_iter=1000,
        early_stopping=True,
        n_iter_no_change=20,
        validation_fraction=0.1,
        random_state=42,
        verbose=False
    )
    model.fit(x_train_scaled, y_train_enc)
    dump(model, "Saved models/mlp_sklearn_credit.joblib")

y_pred_enc = model.predict(x_test_scaled)
y_pred_train_enc = model.predict(x_train_scaled)
y_pred = le.inverse_transform(y_pred_enc)
y_pred_train = le.inverse_transform(y_pred_train_enc)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")

========== Dataset: Credit Score ==========
Softmax selfmade:
Обучение модели:


  1%|          | 529/100000 [00:08<26:13, 63.20it/s]


Accuracy on test: 0.6382666666666666
Accuracy on train: 0.6407857142857143
Confusion matrix: 
[[ 3196    73  2053]
 [  686  4451  3668]
 [ 2042  2330 11501]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.54      0.60      0.57      5322
        Poor       0.65      0.51      0.57      8805
    Standard       0.67      0.72      0.70     15873

    accuracy                           0.64     30000
   macro avg       0.62      0.61      0.61     30000
weighted avg       0.64      0.64      0.64     30000


Softmax library:
Accuracy on test: 0.5807666666666667
Accuracy on train: 0.5821285714285714
Confusion matrix: 
[[  477    80  4765]
 [   59  3797  4949]
 [  301  2423 13149]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.57      0.09      0.15      5322
        Poor       0.60      0.43      0.50      8805
    Standard       0.58      0.83      0.68     15873

    accuracy       

100%|██████████| 50/50 [11:34<00:00, 13.89s/it]


Accuracy on test: 0.6183333333333333
Accuracy on train: 0.6297
Confusion matrix: 
[[ 1134    58  4130]
 [  154  4193  4458]
 [  605  2045 13223]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.60      0.21      0.31      5322
        Poor       0.67      0.48      0.56      8805
    Standard       0.61      0.83      0.70     15873

    accuracy                           0.62     30000
   macro avg       0.62      0.51      0.52     30000
weighted avg       0.62      0.62      0.59     30000


Random Forest library:
Accuracy on test: 0.7057666666666667
Accuracy on train: 0.7191428571428572
Confusion matrix: 
[[ 4327    38   957]
 [  996  5754  2055]
 [ 2839  1942 11092]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.53      0.81      0.64      5322
        Poor       0.74      0.65      0.70      8805
    Standard       0.79      0.70      0.74     15873

    accuracy             

Обучение GBDT: 100%|██████████| 50/50 [01:35<00:00,  1.91s/it]


Accuracy on test: 0.7358
Accuracy on train: 0.7603428571428571
Confusion matrix: 
[[ 3709   123  1490]
 [  481  6120  2204]
 [ 1776  1852 12245]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.62      0.70      0.66      5322
        Poor       0.76      0.70      0.72      8805
    Standard       0.77      0.77      0.77     15873

    accuracy                           0.74     30000
   macro avg       0.72      0.72      0.72     30000
weighted avg       0.74      0.74      0.74     30000


Gradient Boosting Decision Trees library:
Accuracy on test: 0.7788
Accuracy on train: 0.8563142857142857
Confusion matrix: 
[[ 3942    68  1312]
 [  316  6785  1704]
 [ 1339  1897 12637]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.70      0.74      0.72      5322
        Poor       0.78      0.77      0.77      8805
    Standard       0.81      0.80      0.80     15873

    accuracy      

Обучение MLP:   0%|          | 0/1000 [00:00<?, ?it/s]

Эпоха 0, loss=2.277035


Обучение MLP:  20%|██        | 200/1000 [02:16<08:35,  1.55it/s]

Эпоха 200, loss=1.292917


Обучение MLP:  40%|████      | 400/1000 [04:27<06:36,  1.51it/s]

Эпоха 400, loss=1.248351


Обучение MLP:  58%|█████▊    | 580/1000 [06:27<04:40,  1.50it/s]

Остановка на 580 эпохе, change=9.99e-05<eps=0.0001


Accuracy on test: 0.6540333333333334
Accuracy on train: 0.6571
Confusion matrix: 
[[ 3195    69  2058]
 [  865  4800  3140]
 [ 2170  2077 11626]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.51      0.60      0.55      5322
        Poor       0.69      0.55      0.61      8805
    Standard       0.69      0.73      0.71     15873

    accuracy                           0.65     30000
   macro avg       0.63      0.63      0.62     30000
weighted avg       0.66      0.65      0.65     30000


MLP library:
Accuracy on test: 0.7359333333333333
Accuracy on train: 0.8194857142857143
Confusion matrix: 
[[ 3674   101  1547]
 [  138  6432  2235]
 [ 1690  2211 11972]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.67      0.69      0.68      5322
        Poor       0.74      0.73      0.73      8805
    Standard       0.76      0.75      0.76     15873

    accuracy                       

In [3]:
df_credit_balanced = pd.read_csv("C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/Datasets/credit_test1.csv")
x_credit_synth = df_credit_balanced.drop(['Credit_Score'], axis=1).to_numpy()
y_credit_synth = df_credit_balanced['Credit_Score'].to_numpy()

x_train, x_test, y_train, y_test = train_test_split(x_credit_synth, y_credit_synth,
                                                                                                        test_size=0.3, random_state=42)


print("========== Dataset: Credit Score synth balanced ==========")
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)

print("Softmax selfmade:")
softmax_file = "softmax_model_credit_synth.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = SoftmaxClassifier(
        learning_rate=0.1,
        max_iter=100000,
        eps=1e-4,
        lambda_reg=0.05,
        use_pca=True,
        n_components=0.95
    )
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_model_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nSoftmax library:")
softmax_file = "softmax_sklearn_credit_synth.joblib"

if softmax_file in os.listdir("Saved models"):
    model = load("Saved models/" + softmax_file)
else:
    model = LogisticRegression(solver="saga", max_iter=10000, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/softmax_sklearn_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree selfmade:")
tree_file = "decision_tree_model_credit_synth.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTree_classification(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_model_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nDecision Tree library:")
tree_file = "decision_tree_sklearn_credit_synth.joblib"

if tree_file in os.listdir("Saved models"):
    model = load("Saved models/" + tree_file)
else:
    model = DecisionTreeClassifier(max_depth=16)
    model.fit(x_train, y_train)
    dump(model, "Saved models/decision_tree_sklearn_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


"""print("\nRandom Forest selfmade:")
forest_file = "random_forest_model_credit_synth.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForest_classification(max_depth=8, n_trees=50, method="sqrt")
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_model_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")
"""

print("\nRandom Forest library:")
forest_file = "random_forest_sklearn_credit_synth.joblib"

if forest_file in os.listdir("Saved models"):
    model = load("Saved models/" + forest_file)
else:
    model = RandomForestClassifier(max_depth=8, n_estimators=50, random_state=42)
    model.fit(x_train, y_train)
    dump(model, "Saved models/random_forest_sklearn_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees selfmade:")
gbdt_file = "gbdt_model_credit_synth.joblib"

if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = GBDT_with_sklearn_classification(n_estimators=50, max_depth=8, learning_rate=0.1,
                                         subsample=0.85, min_samples_split=20)
    model.fit(x_train, y_train)
    dump(model, "Saved models/gbdt_model_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")


print("\nGradient Boosting Decision Trees library:")
gbdt_file = "gbdt_xgbc_credit_synth.joblib"
if gbdt_file in os.listdir("Saved models"):
    model = load("Saved models/" + gbdt_file)
else:
    model = XGBClassifier(n_estimators=50, max_depth=8)
    model.fit(x_train, y_train_enc, eval_set=[(x_train, y_train_enc)], verbose=False)
    dump(model, "Saved models/gbdt_xgbc_credit_synth.joblib")

y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP selfmade:")
mpl_file = "mlp_model_credit_synth.joblib"

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLP_network(lambda_reg=0.001)
    model.fit(x_train_scaled, y_train_enc, verbose=True)
    dump(model, "Saved models/mlp_model_credit_synth.joblib")

y_pred = model.predict(x_test_scaled)
y_pred_train = model.predict(x_train_scaled)
y_pred_enc = le.inverse_transform(y_pred)
y_pred_train_enc = le.inverse_transform(y_pred_train)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred_enc)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train_enc)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred_enc)}")
print(f"Classification report: \n{classification_report(y_test, y_pred_enc)}")


print("\nMLP library:")
mpl_file = "mlp_sklearn_credit_synth.joblib"

if mpl_file in os.listdir("Saved models"):
    model = load("Saved models/" + mpl_file)
else:
    model = MLPClassifier(
        hidden_layer_sizes=(256, 128, 64, 32),
        activation='relu',
        solver='adam',
        alpha=0.001,
        learning_rate_init=0.01,
        max_iter=1000,
        early_stopping=True,
        n_iter_no_change=20,
        validation_fraction=0.1,
        random_state=42,
        verbose=False
    )
    model.fit(x_train_scaled, y_train_enc)
    dump(model, "Saved models/mlp_sklearn_credit_synth.joblib")

y_pred_enc = model.predict(x_test_scaled)
y_pred_train_enc = model.predict(x_train_scaled)
y_pred = le.inverse_transform(y_pred_enc)
y_pred_train = le.inverse_transform(y_pred_train_enc)
print(f"Accuracy on test: {accuracy_score(y_test, y_pred)}")
print(f"Accuracy on train: {accuracy_score(y_train, y_pred_train)}")
print(f"Confusion matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report: \n{classification_report(y_test, y_pred)}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73000 entries, 0 to 72999
Data columns (total 56 columns):
 #   Column                                              Non-Null Count  Dtype  
---  ------                                              --------------  -----  
 0   Unnamed: 0                                          73000 non-null  int64  
 1   Age                                                 73000 non-null  float64
 2   Occupation_Accountant                               73000 non-null  int64  
 3   Occupation_Architect                                73000 non-null  int64  
 4   Occupation_Developer                                73000 non-null  int64  
 5   Occupation_Doctor                                   73000 non-null  int64  
 6   Occupation_Engineer                                 73000 non-null  int64  
 7   Occupation_Entrepreneur                             73000 non-null  int64  
 8   Occupation_Journalist                               73000 non-null  int64  


Обучение GBDT: 100%|██████████| 50/50 [01:23<00:00,  1.68s/it]


Accuracy on test: 0.757716894977169
Accuracy on train: 0.7788649706457925
Confusion matrix: 
[[6219  164  826]
 [ 811 5572  728]
 [1457 1320 4803]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.73      0.86      0.79      7209
        Poor       0.79      0.78      0.79      7111
    Standard       0.76      0.63      0.69      7580

    accuracy                           0.76     21900
   macro avg       0.76      0.76      0.76     21900
weighted avg       0.76      0.76      0.75     21900


Gradient Boosting Decision Trees library:
Accuracy on test: 0.788675799086758
Accuracy on train: 0.8720939334637965
Confusion matrix: 
[[6376   93  740]
 [ 478 5809  824]
 [1240 1253 5087]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.79      0.88      0.83      7209
        Poor       0.81      0.82      0.81      7111
    Standard       0.76      0.67      0.71      7580

    accuracy  

Обучение MLP:   0%|          | 0/1000 [00:00<?, ?it/s]

Эпоха 0, loss=1.783977


Обучение MLP:  20%|██        | 200/1000 [01:52<07:14,  1.84it/s]

Эпоха 200, loss=1.295207


Обучение MLP:  40%|████      | 400/1000 [03:42<05:23,  1.85it/s]

Эпоха 400, loss=1.257108


Обучение MLP:  53%|█████▎    | 531/1000 [04:49<04:15,  1.84it/s]

Остановка на 531 эпохе, change=9.98e-05<eps=0.0001


Accuracy on test: 0.6875342465753425
Accuracy on train: 0.6925636007827789
Confusion matrix: 
[[5906  219 1084]
 [1116 4821 1174]
 [1608 1642 4330]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.68      0.82      0.75      7209
        Poor       0.72      0.68      0.70      7111
    Standard       0.66      0.57      0.61      7580

    accuracy                           0.69     21900
   macro avg       0.69      0.69      0.69     21900
weighted avg       0.69      0.69      0.68     21900


MLP library:
Accuracy on test: 0.7472602739726028
Accuracy on train: 0.8352641878669276
Confusion matrix: 
[[6234  236  739]
 [ 474 5632 1005]
 [1548 1533 4499]]
Classification report: 
              precision    recall  f1-score   support

        Good       0.76      0.86      0.81      7209
        Poor       0.76      0.79      0.78      7111
    Standard       0.72      0.59      0.65      7580

    accuracy                           0.