In [2]:
import os
import pandas as pd
from Neural_Network_model.MLP_network import MLP_network
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from joblib import dump, load

In [ ]:
train = pd.read_csv('C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/train.csv')
test = pd.read_csv('C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/test.csv')
x_train = train.drop(["Activity", "subject"], axis=1).to_numpy()
y_train = train['Activity'].to_numpy()
x_test = test.drop(["Activity", "subject"], axis=1).to_numpy()
y_test = test['Activity'].to_numpy()

file = "MLP_network.joblib"
if file in os.listdir("C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/Neural_Network_model"):
    network = load("MLP_network.joblib")
else:
    network = MLP_network(max_epochs=1000, activation_fanction="relu", learning_rate=0.1)
    network.fit(x_train, y_train, verbose=True)
    dump(network, "MLP_network.joblib")

y_pred = network.predict(x_test)

print(f"Accuracy score: {accuracy_score(y_test, y_pred)}")
print(f"Confusion matrix:\n{confusion_matrix(y_test, y_pred)}")
print(f"Classification report:\n{classification_report(y_test, y_pred)}")

In [2]:
train = pd.read_csv('C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/Datasets/har_train.csv')
test = pd.read_csv('C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/Datasets/har_test.csv')

x_train = train.drop(columns=['Activity', "subject"]).values
y_train = train['Activity'].values
x_test = test.drop(columns=['Activity', "subject"]).values
y_test = test['Activity'].values

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

clf = MLPClassifier(
    hidden_layer_sizes=(256, 128, 64, 32),
    activation='relu',
    solver='adam',
    alpha=0.001,
    learning_rate_init=0.01,
    max_iter=1000,
    early_stopping=True,
    n_iter_no_change=20,
    validation_fraction=0.1,
    random_state=42,
    verbose=False
)

clf.fit(x_train_scaled, y_train_enc)

y_pred_enc = clf.predict(x_test_scaled)

y_pred = le.inverse_transform(y_pred_enc)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9436715303698676
Confusion matrix:
 [[522   1  13   1   0   0]
 [  0 425  66   0   0   0]
 [  0  22 507   3   0   0]
 [  0   0   0 489   5   2]
 [  0   0   0  15 384  21]
 [  0   0   1  12   4 454]]
Report:
                     precision    recall  f1-score   support

            LAYING       1.00      0.97      0.99       537
           SITTING       0.95      0.87      0.91       491
          STANDING       0.86      0.95      0.91       532
           WALKING       0.94      0.99      0.96       496
WALKING_DOWNSTAIRS       0.98      0.91      0.94       420
  WALKING_UPSTAIRS       0.95      0.96      0.96       471

          accuracy                           0.94      2947
         macro avg       0.95      0.94      0.94      2947
      weighted avg       0.95      0.94      0.94      2947

