In [5]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA

In [6]:
train = pd.read_csv('C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/train.csv')
test = pd.read_csv('C:/Users/zheny/PycharmProjects/Machine_learning_human_activity/test.csv')

x_train = train.drop(["Activity", "subject"], axis=1).to_numpy()
y_train = train["Activity"].to_numpy()
x_test = test.drop(["Activity", "subject"], axis=1).to_numpy()
y_test = test["Activity"].to_numpy()

scaler = StandardScaler()
pca = PCA(n_components=0.95)
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
#x_train_har = pca.fit_transform(x_train_har)
#x_test_har = pca.transform(x_test_har)

In [7]:
model = LogisticRegression(solver="saga", max_iter=10000, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9518154054971157
[[527   0  10   0   0   0]
 [  1 426  61   0   0   3]
 [  0  15 517   0   0   0]
 [  0   0   0 493   3   0]
 [  0   0   1   6 396  17]
 [  0   0   0  24   1 446]]
                    precision    recall  f1-score   support

            LAYING       1.00      0.98      0.99       537
           SITTING       0.97      0.87      0.91       491
          STANDING       0.88      0.97      0.92       532
           WALKING       0.94      0.99      0.97       496
WALKING_DOWNSTAIRS       0.99      0.94      0.97       420
  WALKING_UPSTAIRS       0.96      0.95      0.95       471

          accuracy                           0.95      2947
         macro avg       0.96      0.95      0.95      2947
      weighted avg       0.95      0.95      0.95      2947

